env:
  driver_path: '...r'
credential:
  account_username: '...'
  account_password: '...'
  chat_id: '...'
message:
  time_hour: 8
  time_min: 5
  time_range: 0
  messages:
    - 'Good morning beautiful!'
    - 'Rise and shine, my love ğŸ¤'
    - 'Good morning, my sweet coffee addict â˜•ï¸'
    - 'Good morning sunshine'
    - 'Good morning queen ğŸ‘‘'
    - 'Good morning, gorgeous ğŸ’…ğŸ»'
    - 'Good morning, my heart! ğŸ’– '
    - 'Good morning, my pancake lover ğŸ¥'